$(document).ready(function(){
  $(".travelDescription").hide();
  $(".chemistryDescription").hide();
  $(".shilohDescription").hide();
  $(".skiDescription").hide();

	$(".tbox").click(function(){
    	$(".travelDescription").toggle();
  })
  $(".chembox").click(function(){
    	$(".chemistryDescription").toggle();
  })
  $(".treatmentBox").click(function(){
      $(".shilohDescription").toggle();
  })
  $(".skibox").click(function(){
      $(".skiDescription").toggle();
  })
});
